/wj_716n_lidar:
  ros__parameters:
    hostname: "192.168.1.50"
    port: "2110"
    min_ang : -2.35619449
    max_ang : 2.35619449
    range_min : 0.0
    range_max : 30.0
    frequency_scan : 1
    frame_id : "laser"
    angle_increment : 0.00436325
    time_increment : 0.000046296